apiVersion: v1
kind: Service
metadata:
  name: mcp-server
  labels:
    app: mcp-server
spec:
  selector:
    app: mcp-server
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-server
  labels:
    app: mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-server
  template:
    metadata:
      labels:
        app: mcp-server
    spec:
      containers:
        - name: mcp-server
          image: ghcr.io/vultisig/mcp/mcp-server:v1.0.1
          command: ["/app/main", "-http", ":80"]
          ports:
            - containerPort: 80
              name: http
          env:
            - name: EVM_ETHEREUM_URL
              valueFrom:
                configMapKeyRef:
                  name: mcp-config
                  key: eth-rpc-url
            - name: BLOCKCHAIR_API_URL
              valueFrom:
                configMapKeyRef:
                  name: mcp-config
                  key: blockchair-api-url
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
